apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php7-server
  labels:
    app: my-php7-server
spec:
  selector:
    matchLabels:
     app: my-php7-server
  template:
    metadata:
      labels:
        app: my-php7-server
    spec:
      containers:
      - name: my-php7-server
        image: docker.io/ameng/php7-apache2
        env:
        - name: DB_HOST
          value: mysql-service.default.svc.cluster.local
        - name: DB_NAME
          value: demo
        - name: DB_USER
          value: root
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password.txt
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: my-php7-server
spec:
  selector:
    app: my-php7-server
  ports:
    - name: php
      protocol: TCP
      port: 80
      targetPort: 80targetPort: 80
